### ISSUE TITLE
two  slave  server .

### ISSUE THREAD

**Issue by w796933** [SoylentBob/knot-testbench#3]
sir . can you share  tow slave   dns server  config  file ?

**Comment by SoylentBob** [comment]
Hi there. 

Based on the documentation (https://www.knot-dns.cz/docs/2.9/html/configuration.html#master-zone) it should work somewhat like this:

```
remote:
  - id: master
    address: 192.168.1.1@53
  - id: secondary1
    address: 192.168.2.1@53
  - id: secondary2
    address: 192.168.2.2@53

acl:
  - id: notify_from_master
    address: 192.168.1.1
    action: notify

  - id: secondary1_acl
    address: 192.168.2.1
    action: transfer

  - id: secondary2_acl
    address: 192.168.2.2
    action: transfer

  - id: others_acl
    address: 192.168.3.0/24
    action: transfer

zone:
  - domain: example.com
    storage: /var/lib/knot/zones/
    file: example.com.zone
    master: master
    notify: [secondary1, secondary2]
    acl: [notify_from_master, secondary1_acl, secondary2_acl, others_acl]
```

You simply add acl entries for all of the secondary servers that you want to grant access to your zonefiles for and you add a remote for each of the servers and add them to your list of notifies.
